object-storage:
  # 10분 밀리초 단위로 계산
  # 10 * 60 * 1000
  presigned-url-expire-length: 600000
  profile-image-folder-name: profile-image

server:
  http2:
    enabled: true

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

google:
  oauth:
    client-id: 480466554621-vausblddrlibbs5s3d965kavduhhdl9i.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET}

refresh-token:
  # 14일 밀리초 단위로 계산
  # 14 * 24 * 60 * 60 * 1000
  expire-length: 1209600000

jwt:
  secret-key: ${JWT_SECRET_KEY}
  # 1시간 밀리초 단위로 계산
  # 1 * 60 * 60 * 1000
  expire-length: 3600000

oci:
  object-storage:
    endpoint: https://objectstorage.ap-chuncheon-1.oraclecloud.com
    namespace: ${OCI_OBJECT_STORAGE_NAME_SPACE}
    bucket-name: tag-profile-image
    region: ap-chuncheon-1
    tenancy-id: ${OCI_OBJECT_STORAGE_TENANCY_ID}
    user-id: ${OCI_OBJECT_STORAGE_USER_ID}
    fingerprint: ${OCI_OBJECT_STORAGE_FINGER_PRINT}
    private-key: ${OCI_OBJECT_STORAGE_PRIVATE_KEY}

tag:
  front-domain: http://localhost:3000

encryption:
  password: ${ENCRYPTION_PASSWORD}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,prometheus
#  prometheus:
#    metrics:
#      export:
#        enabled: true

---

spring:
  config:
    activate:
      on-profile: prod

# 하나의 로그 파일에 10MB 저장
logging:
  file:
    path: /var/log/tag
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    sql: debug

server:
  port: 443
  ssl:
    key-store: ${SSL_KEY_STORE_PATH}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true

---

spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    sql: debug
